[package]
name = "xanovi"
version = "0.1.0"
edition = "2021"

[dependencies]
schwi = { path = "../schwi" }
pawnote = { path = "../pawnote" }
tokio = { version = "1.48.0", features = ["full"]}
tokio-macros = "2.6.0"
