[package]
name = "pawnote"
version = "0.1.0"
edition = "2021"

[dependencies]
schwi = { path = "../schwi" }
aes = "0.8"
cbc = "0.1"
md-5 = "0.10"
rsa = { version = "0.9", features = ["pem"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4.42"
url = "2.5.7"
